In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
df = pd.read_csv("Clean Data.csv")

### Using Train Test Split on df

In [3]:
X = df.drop('LoanStatus Yes', axis=1)

In [ ]:
y = df['LoanStatus Yes']

In [ ]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 101)

# Building a Logistic Regression Model

In [7]:
from sklearn.linear_model import LogisticRegression

In [9]:
logmodel = LogisticRegression()

In [10]:
logmodel.fit(X_train, y_train)

C:\Users\dell\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [11]:
predictions_log = logmodel.predict(X_test)

In [12]:
from sklearn.metrics import classification_report

In [13]:
print(classification_report(y_test, predictions_log))

              precision    recall  f1-score   support

           0       0.93      0.41      0.57        64
           1       0.76      0.98      0.86       121

   micro avg       0.78      0.78      0.78       185
   macro avg       0.84      0.69      0.71       185
weighted avg       0.82      0.78      0.76       185



In [14]:
#Confusion Matrix
from sklearn.metrics import confusion_matrix

In [15]:
confusion_matrix(y_test, predictions_log)

array([[ 26,  38],
       [  2, 119]], dtype=int64)

Hence, the logistic regression model attained accuracy of 82%

# Building a Naive Bayes Classifier

In [16]:
from sklearn.naive_bayes import GaussianNB

In [17]:
model_nb = GaussianNB()

In [18]:
model_nb.fit(X_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [19]:
predictions_nb = model_nb.predict(X_test)

In [20]:
print(classification_report(y_test, predictions_nb))

              precision    recall  f1-score   support

           0       0.93      0.41      0.57        64
           1       0.76      0.98      0.86       121

   micro avg       0.78      0.78      0.78       185
   macro avg       0.84      0.69      0.71       185
weighted avg       0.82      0.78      0.76       185



In [21]:
confusion_matrix(y_test, predictions_nb)

array([[ 26,  38],
       [  2, 119]], dtype=int64)

# Building a Decision Tree Model

In [22]:
from sklearn.tree import DecisionTreeClassifier

In [23]:
dtree = DecisionTreeClassifier()

In [24]:
dtree.fit(X_train, y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
            max_features=None, max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, presort=False, random_state=None,
            splitter='best')

In [25]:
predictions_dtree = dtree.predict(X_test)

In [26]:
print(classification_report(y_test, predictions_dtree))

              precision    recall  f1-score   support

           0       0.54      0.47      0.50        64
           1       0.74      0.79      0.76       121

   micro avg       0.68      0.68      0.68       185
   macro avg       0.64      0.63      0.63       185
weighted avg       0.67      0.68      0.67       185



In [27]:
print(confusion_matrix(y_test, predictions_dtree))

[[30 34]
 [26 95]]


Hence, the decision tree model attained accuracy of 67%.

# Building a Random Forest Classifier

In [28]:
from sklearn.ensemble import RandomForestClassifier

In [29]:
rfc = RandomForestClassifier(n_estimators=300)

In [30]:
rfc.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=300, n_jobs=None,
            oob_score=False, random_state=None, verbose=0,
            warm_start=False)

In [31]:
rfc_pred = rfc.predict(X_test)

In [32]:
print(classification_report(y_test, rfc_pred))

              precision    recall  f1-score   support

           0       0.79      0.47      0.59        64
           1       0.77      0.93      0.84       121

   micro avg       0.77      0.77      0.77       185
   macro avg       0.78      0.70      0.72       185
weighted avg       0.78      0.77      0.76       185



In [33]:
print(confusion_matrix(y_test, rfc_pred))

[[ 30  34]
 [  8 113]]
